spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:40019/moviedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    name: movieDatasource
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: update
#            create-source: metadata
#            scripts:
#              action: update
#              create-target: update.sql

      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        jdbc:
          fetch_size: 2000
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        hbm2dll:
          create_namespaces: true
        default_schema: public


server:
  port: 8081

service:
  client:
    url:
      tmdb-service: ${TMDB_URL:https://api.themoviedb.org/3/}
    secrets:
      tmdb-secret: ${TMBD_SECRET:14e1a56e4d03b85e51b78fcfd6e055ec}

jwt:
  secret: jwtsecret