INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('Athena', 'Hours after the tragic death of their youngest brother in unexplained circumstances, three siblings have their lives thrown into chaos.', '2022-09-09', 'https://image.tmdb.org/t/p/original//s8B0GsFEebd0DW2spykLMxnc1Kn.jpg', 'https://www.youtube.com/watch?v=vRunUkdkK8s&pp=ygUUYXRoZW5hIHRyYWlsZXIgbW92aWU%3D');

INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('Cruella', 'In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.', '2021-05-26', 'https://image.tmdb.org/t/p/original//wToO8opxkGwKgSfJ1JK8tGvkG6U.jpg', 'https://www.youtube.com/watch?v=gmRKv7n2If8&pp=ygUVY3J1ZWxsYSBtb3ZpZSB0cmFpbGVy');

INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('Fast & Furious Presents: Hobbs & Shaw', 'Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have traded smack talk and body blows. But when cyber-genetically enhanced anarchist Brixton''s ruthless actions threaten the future of humanity, they join forces to defeat him.', '2019-08-01', 'https://image.tmdb.org/t/p/original//qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg', 'https://www.youtube.com/watch?v=FUK2kdPsBws&pp=ygUaZmFzdCBhbmQgZnVyaW91cyA5IHRyYWlsZXI%3D');

INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('20th Century Girl', 'Yeon-du asks her best friend Bora to collect all the information she can about Baek Hyun-jin while she is away in the U.S. for heart surgery. Bora decides to get close to Baek''s best friend, Pung Woon-ho first. However, Bora''s clumsy plan unfolds in an unexpected direction. In 1999, a year before the new century, Bora, who turns seventeen, falls into the fever of first love.', '2022-10-06', 'https://image.tmdb.org/t/p/original//qhWPZdEEyht9Vqpj0vl3FB6CSr0.jpg', 'https://www.youtube.com/watch?v=KFS4_qevE7M&pp=ygUaMjB0aCBjZW50dXJ5IGdpcmwgdHJhaWxlciA%3D');

INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('Scream', 'After a series of mysterious deaths befalls their small town, an offbeat group of friends become the target of a masked killer.', '1996-12-20', 'https://image.tmdb.org/t/p/original//3O3klyyYpAZBBE4n7IngzTomRDp.jpg', 'https://www.youtube.com/watch?v=h74AXqw4Opc&pp=ygUQc2NyZWFtIDYgdHJhaWxlcg%3D%3D');

INSERT INTO movie (title, overview, release_date, poster_path, trailer_link)
VALUES ('Jeepers Creepers: Reborn', 'Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.', '2022-09-15', 'https://image.tmdb.org/t/p/original//aGBuiirBIQ7o64FmJxO53eYDuro.jpg', 'https://www.youtube.com/watch?v=6D0yFgZnmYM&pp=ygUfamVlcGVycyBjcmVlcGVycyByZWJvcm4gdHJhaWxlcg%3D%3D');


INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Tetris', 'In 1988, American video game salesman Henk Rogers discovers the video game Tetris. When he sets out to bring the game to the world, he enters a dangerous web of lies and corruption behind the Iron Curtain.', '2023-03-15', 'https://image.tmdb.org/t/p/original//4F2QwCOYHJJjecSvdOjStuVLkpu.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('¡Que Viva México!', 'After his grandfather''s death, a man travels with his wife and kids to his hometown, where chaos ensues with his relatives over the inheritance.', '2023-03-23', 'https://image.tmdb.org/t/p/original//ieyUpr5ES9QEz1cn4clCnBf9XJl.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Venom: Let There Be Carnage', 'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.', '2021-09-30', 'https://image.tmdb.org/t/p/original//rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('To Me, the One Who Loved You', 'Koyomi Hidaka and Shiori Sato meet at his father’s research center and begin to fall in love, but so do their parents, who eventually marry. To avoid becoming stepsiblings, they decide to run away to a parallel universe. Traveling between dimensions is common in their world, but not without repercussions. Does a universe exist for the young couple, and what will it cost them to find it?', '2022-10-07', 'https://image.tmdb.org/t/p/original//gt7kD8MjObtgQYH130pZiLTN0qx.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Berserk: The Golden Age Arc II - The Battle for Doldrey', 'The Band of the Hawk participates in the Midland war campaign. On the bloody battlefield, they conquer decisive victories that lead them to Doldrey, an old fortress that will decide the outcome of the war.', '2012-06-23', 'https://image.tmdb.org/t/p/original//gzVQQaDazukAcmiFx6l9WLj1kwo.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Coraline', 'A young girl discovers an idealized parallel universe behind a secret door in her new home, unaware that it contains a sinister secret.', '2009-02-05', 'https://image.tmdb.org/t/p/original//nUiumSEJAHtlmtOptoHEbhWJXk9.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Mighty Morphin Power Rangers: Once & Always', 'After tragedy strikes, an unlikely young hero takes her rightful place among the Power Rangers to face off against the team''s oldest archnemesis.', '2023-04-19', 'https://image.tmdb.org/t/p/original//vc87upO8vcAGj9OmgH3AIz6ikKB.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Aquaman', 'Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm''s half-human, half-Atlantean brother and true heir to the throne.', '2018-12-07', 'https://image.tmdb.org/t/p/original//uCg2HPY7rBCrh1YGpXam9LH1xKZ.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Evil Dead', 'In 1979, a group of college students find a Sumerian Book of the Dead in an old cabin they''ve rented for a weekend getaway.', '1981-09-10', 'https://image.tmdb.org/t/p/original//uYxQ6xhP3WjqPZtxyAOnZQWnZqn.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('R.M.N.', 'A few days before Christmas, having quit his job in Germany, Matthias returns to his Transylvanian village. He wishes to involve himself more in the education of his son, Rudi, left for too long in the care of his mother, Ana, and to rid him of the unresolved fears that have gripped him. He’s also eager to see his ex-lover Csilla and preoccupied about his old father, Otto. When a few new workers are hired at the small factory that Csilla manages, the peace of the community is disturbed, underlying fears grip the adults, and frustrations, conflicts and passions erupt through the thin sliver of apparent understanding and calm.', '2022-06-03', 'https://image.tmdb.org/t/p/original//kDcEfgF7CUo0IYLIazUYYqxagTG.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond', 'A long-running conspiracy is swirling over a mysterious power wielded by the Queen in Raja, a small country west of Tempest. When a slime who evolved into a Demon Lord named Rimuru Tempest crosses paths with Hiiro, a survivor of the Ogre race, an incredible adventure packed with new characters begins. The power of bonds will be put to the test!', '2022-11-25', 'https://image.tmdb.org/t/p/original//xITip9n9uMAUA0TU6niMXU2tbh0.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Mummy Resurrection', 'When an infamous "cursed" Egyptian sarcophagus falls into the hands of unscrupulous huckster Everett Randolph, he becomes obsessed with resurrecting the mummified princess held within it.', '2023-01-02', 'https://image.tmdb.org/t/p/original//d0pt6KlVvmtG0uhccWjgWfIqJee.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Cazadora', 'In a dystopian future, a mother and her teenage son go hunting in the mountains and encounter a stranger who threatens to upend their relationship.', '2023-01-19', 'https://image.tmdb.org/t/p/original//8QxCd3pSSrj6QqaG4fkNkaJmUa.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Knights of the Zodiac', 'When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?', '2023-04-27', 'https://image.tmdb.org/t/p/original//tBiUXvCqz34GDeuY7jK14QQdtat.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Unhappily Ever After', 'María José and Alfredo are about to celebrate their 20th anniversary and their children give them a trip to the hotel where they celebrated their honeymoon, but a spell will make them repeat the same day.', '2023-01-26', 'https://image.tmdb.org/t/p/original//qiAM7Y8xF8wJDDsjeSuLgzyFGmd.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Fast X', 'Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they''ve ever faced: A terrifying threat emerging from the shadows of the past who''s fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.', '2023-05-17', 'https://image.tmdb.org/t/p/original//jwMMQR69Xz9AYtX4u2uYJgfAAev.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Disquiet', 'After a near-fatal car accident, Sam wakes to discover he is trapped in an abandoned hospital by mysterious and sinister forces that have no intention of letting him leave…', '2023-02-10', 'https://image.tmdb.org/t/p/original//fKuyTfzKMOdwQi150Zu3DVXwi7J.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Shotgun Wedding', 'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.', '2022-12-28', 'https://image.tmdb.org/t/p/original//t79ozwWnwekO0ADIzsFP1E5SkvR.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Phenomena', 'Madrid, Spain, 1998. The many resources and skills of Gloria, Paz and Sagrario, three middle-aged women investigating paranormal events, are put to the test when their leader, Father Pilón, has an unpleasant encounter.', '2023-04-14', 'https://image.tmdb.org/t/p/original//liosTyTUf0ObasR2HLTOrHQlzth.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Sayen', 'Sayen is hunting down the men who murdered her grandmother. Using her training and knowledge of nature, she is able to turn the tables on them, learning of a conspiracy from a corporation that threatens her people''s ancestral lands.', '2023-03-03', 'https://image.tmdb.org/t/p/original//aCy61aU7BMG7SfhkaAaasS0KzUO.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Shark Side of the Moon', 'Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.', '2022-08-12', 'https://image.tmdb.org/t/p/original//v5CfpzxoJDkZxjZAizClFdlEF0U.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Queens on the Run', 'When four women finally take the road trip they planned in high school, they have no idea of the things they''ll bump into sometimes literally.', '2023-04-14', 'https://image.tmdb.org/t/p/original//oUmuwUIofGsgOr05kieD3Q8ELEO.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Gold Run', 'Fredrik isn’t the bravest of men, but now he is faced with a great responsibility and an enormous task - to get the entire Norwegian gold reserve away from the Nazis during the invasion of Norway.', '2022-12-15', 'https://image.tmdb.org/t/p/original//6E4LopmCMUXcMLIv7o3jw1xQrgJ.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('One More Time', 'On her 40th birthday, Amelia makes a fateful wish to be 18 again back in 2002 but soon regrets it when she''s stuck reliving the day over and over again.', '2023-04-21', 'https://image.tmdb.org/t/p/original//wUVuJXnBfNpSwvSDGnqzZ5VUBwP.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Batman: The Doom That Came to Gotham', 'Explorer Bruce Wayne accidentally unleashes an ancient evil, and returns to Gotham after being away for two decades. There, Batman battles Lovecraftian supernatural forces and encounters allies and enemies such as Green Arrow, Ra''s al Ghul, Mr. Freeze, Killer Croc, Two-Face and James Gordon.', '2023-03-10', 'https://image.tmdb.org/t/p/original//hrATQE8ScQceohwInaMluluNEaf.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Prey for the Devil', 'In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.', '2022-10-23', 'https://image.tmdb.org/t/p/original//iCvgemXf2Kpr2LvpDmt5J9NhjKM.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Die Hart', 'Kevin Hart - playing a version of himself - is on a death-defying quest to become an action star. And with a little help from John Travolta, Nathalie Emmanuel, and Josh Hartnett - he just might pull it off.', '2023-02-22', 'https://image.tmdb.org/t/p/original//1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Fall', 'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights', '2022-08-11', 'https://image.tmdb.org/t/p/original//v28T5F1IygM8vXWZIycfNEm3xcL.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Magician''s Elephant', 'Peter is searching for his long-lost sister when he crosses paths with a fortune teller in the market square. His one one question is: is his sister still alive? The answer, that he must find a mysterious elephant and the magician who will conjure it, sets Peter off on a journey to complete three seemingly impossible tasks that will change the face of his town forever.', '2023-03-10', 'https://image.tmdb.org/t/p/original//cAoAgzOCxSytYBqqCQulhXNR3LB.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('H.P. Lovecraft''s Witch House', 'Determined to prove the possibility of alternate dimensions, a graduate student unknowingly unlocks a gateway to unimaginable horror. Based on the H.P. Lovecraft''s short story The Dreams in the Witch House.', '2022-06-29', 'https://image.tmdb.org/t/p/original//5KmscR49WkmuPJKjmK4OUmsRn5C.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Ant-Man and the Wasp: Quantumania', 'Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope''s parents Janet van Dyne and Hank Pym, and Scott''s daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.', '2023-02-15', 'https://image.tmdb.org/t/p/original//ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Super Mario Bros. Movie', 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.', '2023-04-05', 'https://image.tmdb.org/t/p/original//qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Shazam! Fury of the Gods', 'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.', '2023-03-15', 'https://image.tmdb.org/t/p/original//2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Avatar: The Way of Water', 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.', '2022-12-14', 'https://image.tmdb.org/t/p/original//t6HIqrRAclMCA60NsSmeqe9RmNV.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Last Kingdom: Seven Kings Must Die', 'In the wake of King Edward''s death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.', '2023-04-14', 'https://image.tmdb.org/t/p/original//7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Creed III', 'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.', '2023-03-01', 'https://image.tmdb.org/t/p/original//cvsXj3I9Q2iyyIo95AecSd1tad7.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Murder Mystery 2', 'After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.', '2023-03-28', 'https://image.tmdb.org/t/p/original//s1VzVhXlqsevi8zeCMG9A16nEUf.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Evil Dead Rise', 'Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.', '2023-04-12', 'https://image.tmdb.org/t/p/original//mIBCtPvKZQlxubxKMeViO2UrP3q.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Ghosted', 'Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.', '2023-04-18', 'https://image.tmdb.org/t/p/original//liLN69YgoovHVgmlHJ876PKi5Yi.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Scream VI', 'Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.', '2023-03-08', 'https://image.tmdb.org/t/p/original//wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Puss in Boots: The Last Wish', 'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.', '2022-12-07', 'https://image.tmdb.org/t/p/original//kuf6dutpsT0vSVehic3EZIqkOBt.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Adrenaline', 'A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.', '2022-12-15', 'https://image.tmdb.org/t/p/original//qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('John Wick: Chapter 4', 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.', '2023-03-22', 'https://image.tmdb.org/t/p/original//vZloFAK7NmvMGKE7VkF5UHaz0I.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Communion Girl', 'Spain, late 1980s. Newcomer Sara tries to fit in with the other teens in this tight-knit small town in the province of Tarragona. If only she were more like her extroverted best friend, Rebe. They go out one night at a nightclub, on the way home, they come upon a little girl holding a doll, dressed for her first communion. And that''s when the nightmare begins.', '2023-02-10', 'https://image.tmdb.org/t/p/original//sP6AO11a7jWgsmT9T8j9EGIWAaZ.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Pirates Down the Street II: The Ninjas from Across', 'The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his new neighbours, son Billy and ninja daughter Yuka become friends. The pirates challenge the ninjas to the ultimate battle at the village''s annual hexathlon. Who will win the match? Ninjas are faster and more agile of course, but pirates are the best cheats in all of the seven seas...', '2022-04-20', 'https://image.tmdb.org/t/p/original//uDsvma9dAwnDPVuCFi99YpWvBk0.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Cocaine Bear', 'Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.', '2023-02-22', 'https://image.tmdb.org/t/p/original//gOnmaxHo0412UVr1QM5Nekv1xPi.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('65', '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.', '2023-03-02', 'https://image.tmdb.org/t/p/original//rzRb63TldOKdKydCvWJM8B6EkPM.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Pope''s Exorcist', 'Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy''s terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.', '2023-04-05', 'https://image.tmdb.org/t/p/original//9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Gangs of Lagos', 'A group of friends who each have to navigate their own destiny, growing up on the bustling streets and neighborhood of Isale Eko, Lagos.', '2023-04-07', 'https://image.tmdb.org/t/p/original//nGwFsB6EXUCr21wzPgtP5juZPSv.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Kill Boksoon', 'At work, she''s a renowned assassin. At home, she''s a single mom to a teenage daughter. Killing? That''s easy. It''s parenting that''s the hard part.', '2023-02-17', 'https://image.tmdb.org/t/p/original//taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Chupa', 'While visiting family in Mexico, a lonely boy befriends a mythical creature hiding on his grandfather''s ranch and embarks on the adventure of a lifetime.', '2023-04-07', 'https://image.tmdb.org/t/p/original//ra3xm8KFAkwK0CdbPRkfYADJYTB.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Attack on Titan', 'As viable water is depleted on Earth, a mission is sent to Saturn''s moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don''t trust that the Earthlings will leave in peace.', '2022-09-30', 'https://image.tmdb.org/t/p/original//qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Supercell', 'Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Rogers, who is now using William as the main attraction to lead a group of unsuspecting adventurers deep into the eye of the most dangerous supercell ever seen.', '2023-03-17', 'https://image.tmdb.org/t/p/original//gbGHezV6yrhua0KfAgwrknSOiIY.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Mummies', 'Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby.', '2023-01-05', 'https://image.tmdb.org/t/p/original//qVdrYN8qu7xUtsdEFeGiIVIaYd.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Ripper''s Revenge', 'One year on from the notorious Ripper murders, London is terrorised once again by a series of brutal killings. When gruesome letters from the Ripper begin landing on his desk, an innocent reporter finds himself drawn into a deadly mystery, threatening the lives of everyone around him.', '2023-04-03', 'https://image.tmdb.org/t/p/original//cuEIBHTWAvaYkhhS8HfOkhce2MB.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Winnie the Pooh: Blood and Honey', 'Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.', '2023-01-27', 'https://image.tmdb.org/t/p/original//ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Black Panther: Wakanda Forever', 'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.', '2022-11-09', 'https://image.tmdb.org/t/p/original//sv1xJUazXeYqALzczSZ3O6nkH75.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Park', 'A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverland.', '2023-03-02', 'https://image.tmdb.org/t/p/original//hR1jdCw0A9czgsbp45TASkjjBhA.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Marcel the Shell with Shoes On', 'Marcel is an adorable one-inch-tall shell who ekes out a colorful existence with his grandmother Connie and their pet lint, Alan. Once part of a sprawling community of shells, they now live alone as the sole survivors of a mysterious tragedy. But when a documentary filmmaker discovers them amongst the clutter of his Airbnb, the short film he posts online brings Marcel millions of passionate fans, as well as unprecedented dangers and a new hope at finding his long-lost family.', '2022-06-24', 'https://image.tmdb.org/t/p/original//jaYmP4Ct8YLnxWAW2oYkUjeXtzm.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Black Adam', 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.', '2022-10-19', 'https://image.tmdb.org/t/p/original//pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('M3GAN', 'A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll''s programming works too well, she becomes overprotective of her new friend with terrifying results.', '2022-12-28', 'https://image.tmdb.org/t/p/original//d9nBoowhjiiYc4FBNtQkPY7c11H.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Black Warrant', 'A semi-retired special ops assassin and a DEA agent cross paths on separate missions to stop a cyber terrorist organization that has built a dangerous machine threatening to attack the power grid and bring catastrophe to the world.', '2023-01-09', 'https://image.tmdb.org/t/p/original//s95yjWcHbRpS32exC8AeA2LNWXS.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Sisu', 'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.', '2023-01-27', 'https://image.tmdb.org/t/p/original//dHx5yuBb05U9vNaNhIBD7jWyxPk.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Prizefighter: The Life of Jem Belcher', 'At the turn of the 19th century, Pugilism was the sport of kings and a gifted young boxer fought his way to becoming champion of England.', '2022-06-30', 'https://image.tmdb.org/t/p/original//x3PIk93PTbxT88ohfeb26L1VpZw.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Devil Conspiracy', 'The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ultra-rich. But when they steal the Shroud of Turin and clone the DNA of Jesus Christ, all hell breaks loose.', '2023-01-13', 'https://image.tmdb.org/t/p/original//2lUYbD2C3XSuwqMUbDVDQuz9mqz.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Exorcist', 'Ophelia, a young nun recently arriving in the town of San Ramon, is forced to perform an exorcism on a pregnant woman in danger of dying. Just when she thinks her possession has ended, she discovers that the evil presence hasn''t disappeared yet. The director of the award-winning Here Comes the Devil and Late Phases adds a new twist to possession movies in one of this year''s Latin American horror surprises.', '2022-11-02', 'https://image.tmdb.org/t/p/original//d07xtqwq1uriQ1hda6qeu8Skt5m.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Plane', 'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.', '2023-01-12', 'https://image.tmdb.org/t/p/original//qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Amazing Maurice', 'Maurice is a streetwise ginger cat who comes up with a money-making scam by befriending a group of self-taught talking rats. When Maurice and the rodents meet a bookworm called Malicia, their little con soon goes down the drain.', '2022-12-16', 'https://image.tmdb.org/t/p/original//ydhZeUjbzVEFclUpMhLfDZSavUY.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('A Tourist''s Guide to Love', 'After an unexpected break up, a travel executive accepts an assignment to go undercover and learn about the tourist industry in Vietnam. Along the way, she finds adventure and romance with her Vietnamese expat tour guide and they decide to hijack the tour bus in order to explore life and love off the beaten path.', '2023-04-21', 'https://image.tmdb.org/t/p/original//uWkpjbBe4gRZilXRXbYfsMUZMhz.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Knock at the Cabin', 'While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.', '2023-02-01', 'https://image.tmdb.org/t/p/original//dm06L9pxDOL9jNSK4Cb6y139rrG.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Black Widow', 'Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.', '2023-07-07', 'https://image.tmdb.org/t/p/original//5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Suicide Squad', 'Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X where they are heavily-armed and dropped off at the remote, enemy-infused island of Corto Maltese.', '2023-08-04', 'https://image.tmdb.org/t/p/original//kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Doctor Strange in the Multiverse of Madness', 'After the events of "Avengers: Endgame," Dr. Stephen Strange continues his research on the Time Stone. But an old friend turned enemy seeks to destroy every sorcerer on Earth, messing with Strange''s plan and causing him to unleash an unspeakable evil.', '2023-11-23', 'https://image.tmdb.org/t/p/original//9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('The Matrix 4', 'The fourth installment in "The Matrix" franchise. Plot details are currently unknown.', '2023-12-22', 'https://image.tmdb.org/t/p/original//emT8P73ASfVtpKP9XnwA8Dk2AKv.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Jurassic World: Dominion', 'The third installment of the new "Jurassic World" trilogy. Plot details are currently unknown.', '2022-06-10', 'https://image.tmdb.org/t/p/original//wz3MRiMmoz4qX6fWz7z5dSqgEBH.jpg');
INSERT INTO movie (title, overview, release_date, poster_path) VALUES ('Spider-Man: No Way Home', 'The third Spider-Man film in the Marvel Cinematic Universe. Peter Parker''s world has been turned upside down as his identity has been revealed, and he finds himself on the run while seeking help from Doctor Strange.', '2022-12-16', 'https://image.tmdb.org/t/p/original//gbGHezV6yrhua0KfAgwrknSOiIY.jpg');
